export enum CUSTOM_EVENTS {
  LANGUAGE_SELECTED = 'LANGUAGE_SELECTED',
  REQUEST_OTP_CLICKED = 'REQUEST_OTP_CLICKED',
  OTP_VERIFY_CLICKED = 'OTP_VERIFY_CLICKED',
  NEW_BUSINESS_SUBMITTED = 'NEW_BUSINESS_SUBMITTED',
  ADD_NEW_CUSTOMER_CLICKED = 'ADD_NEW_CUSTOMER_CLICKED',
  BOOK_CUSTOMER_CLICKED = 'BOOK_CUSTOMER_CLICKED',
  BOOK_SELECTION_CLICKED = 'BOOK_SELECTION_CLICKED',
  BOOK_CHANGED = 'BOOK_CHANGED',
  CREATE_NEW_BOOK_CLICKED = 'CREATE_NEW_BOOK_CLICKED',
  SEARCH_CLICKED = 'SEARCH_CLICKED',
  SEARCH_TYPED = 'SEARCH_TYPED',
  SEARCH_CLOSED = 'SEARCH_CLOSED',
  NEW_CUSTOMER_SAVED = 'NEW_CUSTOMER_SAVED',
  ADD_NEW_DEBIT_CLICKED = 'ADD_NEW_DEBIT_CLICKED',
  ADD_NEW_CREDIT_CLICKED = 'ADD_NEW_CREDIT_CLICKED',
  KHATA_TRANSACTION_CLICKED = 'KHATA_TRANSACTION_CLICKED',
  KHATA_SMS_CLICKED = 'KHATA_SMS_CLICKED',
  KHATA_CALL_CLICKED = 'KHATA_CALL_CLICKED',
  KHATA_WHATSAPP_CLICKED = 'KHATA_WHATSAPP_CLICKED',
  NEW_TRANSACTION_SAVED = 'NEW_TRANSACTION_SAVED',
  EDIT_TRANSACTION_CLICKED = 'EDIT_TRANSACTION_CLICKED',
  DELETE_TRANSACTION_CLICKED = 'DELETE_TRANSACTION_CLICKED',
  TRANSACTION_DELETED = 'TRANSACTION_DELETED',
  TRANSACTION_WHATSAPP_CLICKED = 'TRANSACTION_WHATSAPP_CLICKED',
  TRANSACTION_SHARE_CLICKED = 'TRANSACTION_SHARE_CLICKED',
  TRANSACTION_SAVED = 'TRANSACTION_SAVED',
  CALL_US_CLICKED = 'CALL_US_CLICKED',
  CHAT_WITH_US_CLICKED = 'CHAT_WITH_US_CLICKED',
  EDIT_PROFILE_CLICKED = 'EDIT_PROFILE_CLICKED',
  EDIT_PROFILE_PHOTO_CLICKED = 'EDIT_PROFILE_PHOTO_CLICKED',
  EDIT_YOUR_NAME_CLICKED = 'EDIT_YOUR_NAME_CLICKED',
  EDIT_BUSINESS_NAME_CLICKED = 'EDIT_BUSINESS_NAME_CLICKED',
  SAVE_PROFILE_CLICKED = 'SAVE_PROFILE_CLICKED',
  LOGOUT_CLICKED = 'LOGOUT_CLICKED',
  LANGUAGE_CHANGE_CLICKED = 'LANGUAGE_CHANGE_CLICKED',
  LANGUAGE_CHANGED = 'LANGUAGE_CHANGED',
  HOME_CLICKED = 'HOME_CLICKED',
  MORE_CLICKED = 'MORE_CLICKED',
  // onBoarding
  LoginScreenView = 'LoginScreenView',
  OnboardingLanguageSelectionDropdown = 'OnboardingLanguageSelectionDropdown',
  OnboardingLanguageSelected = 'OnboardingLanguageSelected',
  UserSelectsLanguage = 'UserSelectsLanguage',
  ViewTnCPolicy = 'ViewTnCPolicy',
  ViewPrivacyPolicy = 'ViewPrivacyPolicy',
  OnboardingCountryPickerClick = 'OnboardingCountryPickerClick',
  OnboardingCountrySelected = 'OnboardingCountrySelected',
  OnboardingRequestOtp = 'OnboardingRequestOtp',
  OnboardingEditNumberClick = 'OnboardingEditNumberClick',
  OnboardingResendOtpClick = 'OnboardingResendOtpClick',
  OnboardingVerifyOtp = 'OnboardingVerifyOtp',
  OnboardingLaunchMainScreen = 'OnboardingLaunchMainScreen',
  OnboardingError = 'OnboardingError',
  UniqueLoginSuccess = 'UniqueLoginSuccess',
  OnboardingCreateLedgerScreenView = 'OnboardingCreateLedgerScreenView',
  OnboardingGetStartedClick = 'OnboardingGetStartedClick',

  // HomePage
  HomePageView = 'HomePageView',
  HomeSidebarMoneyClick = 'HomeSidebarMoneyClick',
  HomeSidebarSettingsClick = 'HomeSidebarSettingsClick',
  AddNewCustomerClick = 'AddNewCustomerClick',
  HomeItemClick = 'HomeItemClick',
  HomeSidebarReportsClick = 'HomeSidebarReportsClick',
  HomePageAddLedgerClick = 'HomePageAddLedgerClick',
  TransactionKebabMenuActionClick = 'TransactionKebabMenuActionClick',
  TransactionKebabMenuEditEntryClick = 'TransactionKebabMenuEditEntryClick',
  TransactionKebabMenuDeleteTransactionClick = 'TransactionKebabMenuDeleteTransactionClick',
  UserNameClick = 'UserNameClick',
  BookProfileAboutUsClick = 'BookProfileAboutUsClick',
  BookProfileAboutKhatabookClick = 'BookProfileAboutKhatabookClick',
  BookProfilePrivacyPolicyClick = 'BookProfilePrivacyPolicyClick',
  BookProfileTermsAndConditionsClick = 'BookProfileTermsAndConditionsClick',
  AddNewLedgerGetStartedClick = 'AddNewLedgerGetStartedClick',
  SaveNewCustomer = 'SaveNewCustomer',
  SaveTransaction = 'SaveTransaction',
  SaveNewTransaction = 'SaveNewTransaction',
  AddTransaction = 'AddTransaction',
  ConfirmDeleteTransactionClick = 'ConfirmDeleteTransactionClick',
  PaymentReminderShareOnWhatsApp = 'PaymentReminderShareOnWhatsApp',
  CustomerKhataOnTransactionClicked = 'CustomerKhataOnTransactionClicked',
  HomeBannerClick = 'HomeBannerClick',
  TryForFreeClick = 'TryForFreeClick',
  // Filtering/Sorting
  HomeFilterClick = 'HomeFilterClick',
  HomeRefreshFilter = 'HomeRefreshFilter',
  HomeRefreshSort = 'HomeRefreshSort',
  HomeRemoveFilterClick = 'HomeRemoveFilterClick',
  // Edit/delete Customer details
  EditCustomerClick = 'EditCustomerClick',
  DeleteCustomerClick = 'DeleteCustomerClick',
  SaveCustomer = 'SaveCustomer',
  AddAddressClick = 'AddAddressClick',
  AddPhoneNumberClick = 'AddPhoneNumberClick',
  SaveAddressClick = 'SaveAddressClick',
  SavePhoneNumberClick = 'SavePhoneNumberClick',
  DeleteCustomerConfirmClick = 'DeleteCustomerConfirmClick',
  DeleteCustomerCancelClick = 'DeleteCustomerCancelClick',
  // Settings
  SettingsBackupInformationClick = 'SettingsBackupInformationClick',
  SettingsRecycleBinClick = 'SettingsRecycleBinClick',
  SettingsDeleteKhataClick = 'SettingsDeleteKhataClick',
  DeleteKhataConfirmClick = 'DeleteKhataConfirmClick',
  RecycleBinOnUndoClicked = 'RecycleBinOnUndoClicked',
  RecycleBinRecoverItemConfirmation = 'RecycleBinRecoverItemConfirmation',
  SettingCurrencyClick = 'SettingCurrencyClick',
  CurrencyDropDownClick = 'CurrencyDropDownClick',
  UserSelectsCurrency = 'UserSelectsCurrency',

  //Profile
  HomeProfileClick = 'HomeProfileClick',
  ProfileClick = 'ProfileClick',
  ProfileSaveClick = 'ProfileSaveClick',
  ProfileSaveConfirmClick = 'ProfileSaveConfirmClick',
  ProfileLogoutClick = 'ProfileLogoutClick',

  // Money tab
  MoneytabAddBankAccountPageView = 'MoneytabAddBankAccountPageView',
  MoneytabKYCPageView = 'MoneytabKYCPageView',
  MoneytabUseQRCodeClick = 'MoneytabUseQRCodeClick',
  PaymentHistoryTransactionsClick = 'PaymentHistoryTransactionsClick',
  PaymentHistorySettlementsClick = 'PaymentHistorySettlementsClick',
  QRCodePlaceOrderClick = 'QRCodePlaceOrderClick',
  QRCodeDownloadQRClick = 'QRCodeDownloadQRClick',
  QRCodeViewOrderClick = 'QRCodeViewOrderClick',
  PaymentHistoryCustomerTransactionClick = 'PaymentHistoryCustomerTransactionClick',
  PaymentHistoryTransactionDateFilterClick = 'PaymentHistoryTransactionDateFilterClick',
  PaymentHistoryTransactionTypeFilterClick = 'PaymentHistoryTransactionTypeFilterClick',
  PaymentHistoryTransactionStatusClick = 'PaymentHistoryTransactionStatusClick',
  PaymentHistoryTransactionDateFilterSetDate = 'PaymentHistoryTransactionDateFilterSetDate',
  PaymentHistoryCustomerSettlementClick = 'PaymentHistoryCustomerSettlementClick',
  PaymentDetailsPageView = 'PaymentDetailsPageView',
  PaymentDetailsViewCharges = 'PaymentDetailsViewCharges',
  PaymentHistorySettlementDateFilterClick = 'PaymentHistorySettlementDateFilterClick',
  PaymentHistorySettlementTypeFilterClick = 'PaymentHistorySettlementTypeFilterClick',
  PaymentHistorySettlementStatusClick = 'PaymentHistorySettlementStatusClick',
  PaymentHistorySettlementDateFilterSetDate = 'PaymentHistorySettlementDateFilterSetDate',

  // SMS Reminders
  CustomerSummarySMSClick = 'CustomerSummarySMSClick',
  SMSerrorLimitExceeded = 'SMSerrorLimitExceeded',
  SMSClickAddPhoneNumberToastClick = 'SMSClickAddPhoneNumberToastClick',
  SendSMSClick = 'SendSMSClick',
  SMSCancelClick = 'SMSCancelClick',

  // contacts
  ChoosefromContactsClick = 'ChoosefromContactsClick',
  AddCustomerManually = 'AddCustomerManually',

  // reports
  ReportsClick = 'ReportsClick',
  DownloadReportsClick = 'DownloadReportsClick',
  ReportsDateSet = 'ReportsDateSet',
  ReportsSearchClicked = 'ReportsSearchClicked',
}
