export enum CUSTOM_EVENTS {
  CUSTOMER_CHANGED = 'CUSTOMER_CHANGED',
  CUSTOMER_DELETED = 'CUSTOMER_DELETED',
  TRANSACTION_CHANGED = 'TRANSACTION_CHANGED',
  TRANSACTION_EDITED = 'TRANSACTION_EDITED',
  TRANSACTION_DELETED = 'TRANSACTION_DELETED',
  SERVICE_WORKER_UPDATED = 'SERVICE_WORKER_UPDATED',
  BOOK_DELETED = 'BOOK_DELETED',
  BOOK_CHANGED = 'BOOK_CHANGED',

  INVOICE_CHANGED = 'INVOICE_CHANGED',

  //new events
  ConfirmDeleteTransactionClick = 'ConfirmDeleteTransactionClick',
}
