export const SENTRY_TAG = {
  ERROR_BOUNDARY: 'ERROR_BOUNDARY',
  ADD_BUSINESS: 'ADD_BUSINESS',
  LANG_PROVIDER: 'LANG_PROVIDER',
  API_HELPER: 'API_HELPER',
  BOOK_LISTING: 'BOOK_LISTING',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  DELETE_BOOK: 'DELETE_BOOK',
  TRANSACTION_FORM: 'TRANSACTION_FORM',
  TRANSACTION_LISTING: 'TRANSACTION_LISTING',
  LOGOUT: 'LOGOUT',
  SYNC: 'SYNC',
  RESTORE_TRANSACTION: 'RESTORE_TRANSACTION',
  RESTORE_CUSTOMER: 'RESTORE_CUSTOMER',
  RESTORE_BOOK: 'RESTORE_BOOK',

  // money tab
  FETCH_INVOICES: 'FETCH_INVOICES',
  FETCH_PAYOUTS: 'FETCH_PAYOUTS',
};
