export const STORAGE_USER_KEY = 'KB_USER';
export const STORAGE_DEVICE_KEY = 'KB_DEVICE';

export const ON_BOARDING_PHONE = 'ON_BOARDING_PHONE';
export const ON_BOARDING_BUSINESS_NAME = 'ON_BOARDING_BUSINESS_NAME';
export const ON_BOARDING_COUNTRY_CODE = 'ON_BOARDING_COUNTRY_CODE';
export const ON_BOARDING_OTP = 'ON_BOARDING_OTP';
export const ON_BOARDING_ENABLE_USER_PREF = 'ON_BOARDING_ENABLE_USER_PREF';
export const ON_BOARDING_OTP_TIMER = 'ON_BOARDING_OTP_TIMER';
